const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT_ERROR_CODE = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT_ERROR_CODE,
  INTERNAL_SERVER_ERROR,
};
